#!/usr/bin/env node
// publish-feed.mjs — export the live signal feed to static files under feed/ so they ship to the PUBLIC
// repo (github.com/sstiempro/mesh) and become real, consumable URLs WITHOUT exposing the local server:
//   feed/latest.json  → raw.githubusercontent.com/sstiempro/mesh/main/feed/latest.json   (poll this)
//   feed/feed.rss     → subscribable in any RSS reader
//   feed/digest.md    → the ready-to-post daily digest
//   feed/index.html   → a tiny public landing (works as a static file; GitHub Pages-ready)
// Generate-only (no git). Run before a public sync:  node tools/publish-feed.mjs
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { publicFeed, digest } from '../dashboard/execution.mjs';

const LAB = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FEEDDIR = path.join(LAB, 'feed');
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const feed = await publicFeed('json');
const rss = await publicFeed('rss');
const dg = await digest();
const alerts = (feed.alerts || []).slice(0, 60);

await mkdir(FEEDDIR, { recursive: true });
await writeFile(path.join(FEEDDIR, 'latest.json'), JSON.stringify({ updated: feed.updated, count: feed.count, tiers: feed.tiers, alerts: feed.alerts?.slice(0, 100) || [] }, null, 2));
await writeFile(path.join(FEEDDIR, 'feed.rss'), rss);
await writeFile(path.join(FEEDDIR, 'digest.md'), dg.markdown);

const rows = alerts.map(a => `<tr><td class="t">${esc(a.type)}</td><td>${esc(a.asset || '')}</td><td>${esc(a.msg || '')}</td><td class="ts">${esc((a.ts || '').slice(5, 16).replace('T', ' '))}</td></tr>`).join('\n');
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>mesh — keyless crypto signal feed</title>
<style>body{background:#0a0f1c;color:#cbd5e1;font:14px/1.5 ui-sans-serif,system-ui,sans-serif;margin:0;padding:24px}
.wrap{max-width:880px;margin:0 auto}h1{font-size:20px;color:#f1f5f9;margin:0 0 2px}.sub{color:#64748b;font-size:12px;margin-bottom:16px}
.tiers{display:flex;gap:8px;margin:12px 0}.tier{border:1px solid #1e293b;border-radius:10px;padding:8px 12px;font-size:12px}
table{width:100%;border-collapse:collapse;font-size:12px}td{padding:6px 8px;border-bottom:1px solid #16203a;vertical-align:top}
.t{color:#38bdf8;white-space:nowrap}.ts{color:#475569;white-space:nowrap}a{color:#38bdf8}.foot{color:#475569;font-size:11px;margin-top:18px}</style></head>
<body><div class="wrap">
<h1>📡 mesh — keyless crypto signal feed</h1>
<div class="sub">Stablecoin depegs · TVL-drain early-warning · funding extremes · real-yield radar · regime. Updated ${esc(feed.updated || '')}. Free tier.</div>
<div class="tiers"><div class="tier"><b>Free</b> — this feed · <a href="latest.json">latest.json</a> · <a href="feed.rss">RSS</a></div>
<div class="tier"><b>Pro</b> — realtime webhook push + private signals → <a href="https://github.com/sstiempro/mesh">sstiempro/mesh</a></div></div>
<table><thead><tr><td class="t">type</td><td>asset</td><td>signal</td><td class="ts">when</td></tr></thead><tbody>
${rows || '<tr><td colspan=4>warming up…</td></tr>'}
</tbody></table>
<div class="foot">Generated by the mesh autonomous monitor loop · keyless · $0 · not financial advice. © sstiempro</div>
</div></body></html>`;
await writeFile(path.join(FEEDDIR, 'index.html'), html);

console.log(`✓ published feed/ — ${alerts.length} alerts · digest counts ${JSON.stringify(dg.counts)}`);
console.log(`  public URLs after push: raw.githubusercontent.com/sstiempro/mesh/main/feed/latest.json (+ feed.rss, index.html)`);
